### ISSUE TITLE
Dosent load files

### ISSUE THREAD

**Issue by Alexlytle** [smarteist/wordpress-router#2]
I tried this on blank underscore theme it says missing class
Fatal error: Uncaught Error: Class 'Hexbit\Router\WordPress\Router' not found in

Getting started documentation sucks

**Comment by smarteist** [comment]
> I tried this on blank underscore theme it says missing class Fatal error: Uncaught Error: Class 'Hexbit\Router\WordPress\Router' not found in
> 
> Getting started documentation sucks

You can run ```composer remove hexbit/router```, and easily remove this library XD.
